trigger: none

schedules:
- cron: "0 8 * * Mon-Fri" # First number represent the amount of minutes, second represent the hours. In this case 08:00 Monday - Friday
  displayName: Stop Self Hosted Agent Container
  branches:
    include: 
    - master
  always: true

pool: "Hosted VS2017"

variables:
  ResourceGroupName: 'rg-tyrell-app-001'
  ACIname: 'aci-tyrell-app-001'
  ServiceConnection: 'Tyrell-MSDN'

# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# =-=                                               DON't CHANGE ANYTHING BELOW THIS LINE!!                                                     =-=
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

steps:
- task: AzurePowerShell@4
  inputs:
    azureSubscription: $(ServiceConnection)
    ScriptType: 'FilePath'
    ScriptPath: 'powershell-scripts/StartContainer.ps1'
    ScriptArguments: '-ResourceGroupName $(ResourceGroupName) -ResourceName $(ACIname)'
    azurePowerShellVersion: 'LatestVersion'